name: Publish Docs to GitHub Pages

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: dev

      - name: Deploy MkDocs
        run: pixi run -e dev mkdocs gh-deploy --force